version: "3"
services:
  db:
    image: "postgres"
    container_name: "db-base"
    environment:
      - POSTGRES_USER=shun
      - POSTGRES_PASSWORD=smilehu
      - POSTGRES_DB=db-base
    ports:
      - "35432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  db-test:
    image: "postgres"
    container_name: "db-base_test"
    environment:
      - POSTGRES_USER=shun
      - POSTGRES_PASSWORD=smilehu
      - POSTGRES_DB=db-base_test
    ports:
      - "45432:5432"
    volumes:
      - ./test-db:/var/lib/postgresql/data
